# This is a config for E2B sandbox template.
# You can use template ID (zloe04fcjvm1tmvt153a) or template name (lovable-test-5) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-test-5") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-test-5") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-test-5')

team_id = "28663260-ed6f-48f7-8252-74ea9189c6f0"
start_cmd = '"/compile_page.sh"'
dockerfile = "e2b.Dockerfile"
template_name = "lovable-test-5"
template_id = "zloe04fcjvm1tmvt153a"
